%define LEFT_ARROW 4Bh
%define RIGHT_ARROW 4Dh
%define UP_ARROW 48h
%define DOWN_ARROW 50h
; BUTTONS 1ST
%define U_KEY 16h
%define I_KEY 17h
%define J_KEY 24h
%define K_KEY 25h
%define N_KEY 31h
%define M_KEY 32h

%define W_KEY 11h
%define A_KEY 1Eh
%define S_KEY 1Fh
%define D_KEY 20h
; BUTTONS 2ND
%define R_KEY 13h
%define T_KEY 14h
%define F_KEY 21h
%define G_KEY 22h
%define C_KEY 2Eh
%define V_KEY 2Fh

%define ESCAPE_KEY 01h
%define ENTER_KEY 1Ch